var DATA_TYPES={members:['member_id','member_name*','phone','verification_status'],contracts:['member_id','member_name*','phone','studio_code*','nest_id*','start_date*','end_date*','monthly_rent*','deposit','document_status','check_in'],bookings:['action*','booking_id','studio_code','nest_id','member_name','arrive','depart','status','rate','reason'],collections:['contract_id*','amount*','due_date*','kind','owner','note'],payments:['receivable_id*','amount*','reference*','method'],clocks:['studio_code*','counted_nests*','vacant_nests*','evidence*','physical_count*','vacant_verified*','collections_reviewed*'],studios:['studio_code*','capacity','owner','clock_due_at']};
var HELP={action:'create, checkin, checkout or cancel',document_status:'pending or signed',check_in:'true or false',status:'reserved or in',verification_status:'needs_review or verified',physical_count:'true or false',vacant_verified:'true or false',collections_reviewed:'true or false'};
function q(id){return document.getElementById(id)}
function api(url,body){return fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}).then(function(r){return r.json().then(function(j){if(!r.ok)throw j;return j})})}
function fields(){var type=q('entry-type').value; q('entry-fields').innerHTML=DATA_TYPES[type].map(function(raw){var required=raw.slice(-1)==='*',name=raw.replace('*',''),kind=/_date$|^arrive$|^depart$/.test(name)?'date':/amount|rent|deposit|capacity|nests/.test(name)?'number':'text';return '<div><label>'+name.replace(/_/g,' ')+(required?' *':'')+'</label><input data-key="'+name+'" type="'+kind+'" '+(required?'required':'')+'><div class="field-help">'+(HELP[name]||'')+'</div></div>'}).join('')}
function formRow(){var row={};q('entry-fields').querySelectorAll('[data-key]').forEach(function(input){row[input.dataset.key]=input.value});return row}
function show(value,bad){q('data-result').textContent=typeof value==='string'?value:JSON.stringify(value,null,2);q('data-result').className='statusline data-result'+(bad?' bad':'')}
function submitRows(table,rows,commit,filename){if(!rows.length){show('No data rows found.',true);return Promise.reject({error:'rows_required'})}show(commit?'Saving…':'Validating…');return api('/api/bison/data/import',{table:table,rows:rows,commit:commit,filename:filename||'browser entry'}).then(function(result){show((commit?'Saved ':'Validated ')+result.valid+' row(s). Dashboard users will receive the update within 15 seconds.');return result}).catch(function(error){show(error.errors?error.errors.map(function(x){return 'Row '+x.row+': '+x.error+(x.message?' — '+x.message:'')}).join('\n'):(error.message||error.error||'Failed'),true);throw error})}
function csv(text){var rows=[],row=[],cell='',quote=false;for(var i=0;i<text.length;i++){var c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){cell+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(function(x){return x.trim()}))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(function(x){return x.trim()}))rows.push(row);if(rows.length<2)return[];var head=rows[0].map(function(x){return x.trim().toLowerCase().replace(/\s+/g,'_').replace(/\*/g,'')});return rows.slice(1).filter(function(values){return values.some(function(x){return x.trim()})}).map(function(values){var out={};head.forEach(function(h,j){out[h]=(values[j]||'').trim()});return out})}
function template(){var type=q('upload-type').value,headers=DATA_TYPES[type].map(function(x){return x.replace('*','')});var sample=headers.map(function(h){return HELP[h]||''});var content=headers.join(',')+'\r\n'+sample.map(function(x){return /[,"\n]/.test(x)?'"'+x.replace(/"/g,'""')+'"':x}).join(',')+'\r\n';var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/csv'}));a.download='bison-'+type+'-template.csv';a.click();URL.revokeObjectURL(a.href)}
q('entry-type').onchange=fields;fields();q('entry-form').onsubmit=function(e){e.preventDefault();submitRows(q('entry-type').value,[formRow()],true,'browser entry').then(function(){q('entry-form').reset();fields()}).catch(function(){})};q('download-template').onclick=template;var uploaded=[];q('csv-file').onchange=function(){var file=this.files[0];if(!file)return;file.text().then(function(text){uploaded=csv(text);q('upload-count').textContent=uploaded.length+' data row(s) ready'})};q('validate-upload').onclick=function(){submitRows(q('upload-type').value,uploaded,false,q('csv-file').files[0]&&q('csv-file').files[0].name).catch(function(){})};q('commit-upload').onclick=function(){submitRows(q('upload-type').value,uploaded,true,q('csv-file').files[0]&&q('csv-file').files[0].name).catch(function(){})};
api('/api/bison/data/config').then(function(x){q('sheet-url').value=x.config.url||'';q('sheet-enabled').checked=!!x.config.enabled});q('sheet-form').onsubmit=function(e){e.preventDefault();api('/api/bison/data/config',{url:q('sheet-url').value,enabled:q('sheet-enabled').checked}).then(function(x){show(x.message)}).catch(function(x){show(x.message||x.error,true)})};
