export function booksMarkup(data,month,account,{t,esc,money}){
  const rupees=n=>money(n/100),monthLabel=m=>new Date(m+'-01T12:00:00Z').toLocaleDateString(document.documentElement.lang+'-IN',{month:'long',year:'numeric'});
  const intro=`<div class="service-intro"><div class="eyebrow">SEND · NIABOOKS</div><h1>${t('Your work. Your money. Your story.','आपका काम। आपका पैसा। आपकी कहानी।')}</h1><p>${t('See what you earn, what you spend and what reaches home.','देखें कितना कमाया, कितना खर्च हुआ और कितना घर पहुँचा।')}</p></div>`;
  if(!account)return intro+`<section class="panel stack"><h2>NiaBooks</h2><p>${t('Sign in to see your personal money statement.','अपना पैसे का विवरण देखने के लिए साइन इन करें।')}</p><button class="primary" data-action="login">${t('Sign in','साइन इन')}</button></section>`;
  if(!data?.months?.length)return intro+`<section class="panel stack"><h2>${t('Your money story starts here.','आपके पैसे की कहानी यहाँ शुरू होती है।')}</h2><p>${esc(data?.error||t('Your statement will appear when your Nia team connects verified financial records.','निया टीम से पुष्टि किए गए वित्तीय रिकॉर्ड जुड़ने पर आपका विवरण यहाँ दिखेगा।'))}</p><p class="muted">${t('No score yet. Missing information is not a low score.','अभी स्कोर नहीं है। जानकारी की कमी का मतलब कम स्कोर नहीं है।')}</p><button data-action="books-refresh">${t('Refresh statement','विवरण ताज़ा करें')}</button></section>`;
  const m=data.months.find(m=>m.month===month)||data.months.at(-1),tot=m.totals,score=data.score;
  const labels={earning:t('Earnings','कमाई'),expense:t('Expenses','खर्च'),home:t('Sent home','घर भेजा'),refund:t('Refund','वापसी')};
  const scoreReason=score.reason==='consent_required'?t('Choose whether to calculate your Nia health score.','चुनें कि आप अपना निया हेल्थ स्कोर निकालना चाहते हैं या नहीं।'):score.reason==='source_stale'?t('Refresh your records before calculating a score.','स्कोर निकालने से पहले रिकॉर्ड ताज़ा करें।'):t('We need three complete months of verified records. Missing information is not a low score.','हमें तीन पूरे महीनों के पुष्टि किए गए रिकॉर्ड चाहिए। जानकारी की कमी का मतलब कम स्कोर नहीं है।');
  return intro+`<div class="books-toolbar"><label>${t('Your monthly statement','आपका मासिक विवरण')}<select data-books-month>${[...data.months].reverse().map(x=>`<option value="${esc(x.month)}" ${x.month===m.month?'selected':''}>${esc(monthLabel(x.month))}</option>`).join('')}</select></label><button data-action="books-refresh">${t('Refresh statement','विवरण ताज़ा करें')}</button><button data-action="books-download">${t('Download statement','विवरण डाउनलोड करें')}</button></div>
  <p class="muted">${data.preview?t('Example statement · Fictional amounts for this demo.','उदाहरण विवरण · इस डेमो के लिए काल्पनिक राशियाँ।'):''} ${data.status==='stale'?t('Records need refreshing.','रिकॉर्ड ताज़ा करने की ज़रूरत है।'):''}</p>
  <div class="books-summary">${[['earned',t('You earned','आपने कमाया')],['spent',t('You spent','आपने खर्च किया')],['home',t('You sent home','आपने घर भेजा')],['left',t('Left after outgoings','खर्च के बाद बाकी')]].map(([key,label])=>`<section class="panel"><span>${label}</span><strong>${rupees(tot[key])}</strong></section>`).join('')}</div>
  <p class="books-note">${t('Recorded earnings − expenses − money sent home + refunds. This is a cash-flow summary, not your bank balance.','दर्ज कमाई − खर्च − घर भेजा पैसा + वापसी। यह पैसे के आने-जाने का सार है, बैंक बैलेंस नहीं।')} ${tot.refunds?t('Refunds','वापसी')+': '+rupees(tot.refunds):''}</p>
  <div class="books-layout"><section class="panel books-statement"><h2>${t('Money in. Money out.','पैसा आया। पैसा गया।')}</h2><p class="muted">${esc(monthLabel(m.month))} · ${m.complete?t('Complete example history','पूरा उदाहरण विवरण'):t('Partial records','अधूरे रिकॉर्ड')}</p><div class="books-lines">${[...m.entries].sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<details class="books-entry"><summary><span><b>${esc(t(e.label))}</b><small>${esc(e.date)} · ${labels[e.kind]}${e.status!=='settled'?' · '+esc(e.status):''}</small></span><strong>${['earning','refund'].includes(e.kind)?'+':'−'}${rupees(e.amountPaise)}</strong></summary><p>${t('Source','स्रोत')}: ${esc(e.source)}<br>${t('Reference','संदर्भ')}: ${esc(e.reference)}<br>${data.preview?t('Illustrative source record','स्रोत रिकॉर्ड का उदाहरण'):esc(e.status)}</p></details>`).join('')}</div>${m.pending?`<p>${t('Pending entries are excluded from totals.','लंबित प्रविष्टियाँ कुल में शामिल नहीं हैं।')}</p>`:''}<button data-action="help">${t('Something looks wrong? Ask your Nia team','कुछ गलत लग रहा है? निया टीम से पूछें')}</button></section>
  <aside class="books-side"><section class="panel stack books-health"><div class="row"><h2>${t('Nia health','निया हेल्थ')}</h2><span class="badge">${t('Experimental','प्रायोगिक')}</span></div>${score.status==='ready'?`<div class="books-score"><strong>${score.value}</strong><span>/ 100</span></div><p>${t('Based on your last three complete months.','आपके पिछले तीन पूरे महीनों के आधार पर।')}</p><label>${t('Money retained','बचाया गया पैसा')} <b>${score.retainedPoints}/60</b><meter min="0" max="60" value="${score.retainedPoints}">${score.retainedPoints}</meter></label><label>${t('Income consistency','कमाई की नियमितता')} <b>${score.stabilityPoints}/40</b><meter min="0" max="40" value="${score.stabilityPoints}">${score.stabilityPoints}</meter></label>`:`<h3>${t('Build your money picture','अपने पैसे की तस्वीर बनाएँ')}</h3><p>${scoreReason}</p>`}<p class="muted">${t('A view of cash-flow health. Not a CIBIL score, credit rating or loan approval.','पैसे के आने-जाने की स्थिति। यह CIBIL स्कोर, क्रेडिट रेटिंग या ऋण की मंज़ूरी नहीं है।')}</p><details><summary>${t('How it works','यह कैसे काम करता है')}</summary><p>${t('Money retained: up to 60 points, reaching 60 when 20% of recorded income remains after expenses and transfers. Income consistency: up to 40 points, using the lowest monthly income divided by the highest across three months. These trial weights are not validated for lending.','बचाया गया पैसा: अधिकतम 60 अंक, जब खर्च और ट्रांसफ़र के बाद दर्ज आय का 20% बचता है। कमाई की नियमितता: तीन महीनों की सबसे कम आय को सबसे अधिक आय से भाग देकर अधिकतम 40 अंक। इन प्रयोगात्मक वज़नों की ऋण के लिए पुष्टि नहीं हुई है।')}</p></details><p>${t('Optional. Used only for this statement; it does not change your access to Nia services.','वैकल्पिक। केवल इस विवरण के लिए; निया सेवाओं तक आपकी पहुँच नहीं बदलती।')}</p><button data-action="books-consent" data-id="${data.consent?'off':'on'}">${data.consent?t('Turn off my score','मेरा स्कोर बंद करें'):t('Show my Nia health score','मेरा निया हेल्थ स्कोर दिखाएँ')}</button></section><p class="books-note">${t('Records refreshed','रिकॉर्ड ताज़ा किए गए')}: ${esc(new Date(data.asOf).toLocaleString())}</p></aside></div>`;
}
export function downloadBooks(data,month){
  const m=data?.months?.find(m=>m.month===month)||data?.months?.at(-1);if(!m)return;
  const cell=v=>'"'+String(v).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';
  const rows=[['NiaBooks',data.preview?'ILLUSTRATIVE DEMO':'Recorded statement',m.month],['Not a bank balance. Pending/failed rows excluded from totals.'],['Date','Description','Type','Amount INR','Status','Source','Reference'],...m.entries.map(e=>[e.date,e.label,e.kind,(e.amountPaise/100).toFixed(2),e.status,e.source,e.reference]),[],['Earnings',m.totals.earned/100],['Expenses',m.totals.spent/100],['Sent home',m.totals.home/100],['Refunds',m.totals.refunds/100],['Left after outgoings',m.totals.left/100]];
  const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`NiaBooks-${m.month}${data.preview?'-example':''}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
