import { planCard } from './commerce-plan.js';
// Partner actions remain informational until Central enables consented referrals.
export function healthSupportMarkup(t){
  const icon=path=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
  return `<div class="books-support" role="group" aria-label="${t('Nia health support')}"><button class="books-support-action" data-action="books-loans"><span class="books-support-icon">${icon('<path d="M3 10h18M5 10v9m5-9v9m4-9v9m5-9v9M3 21h18M3 6l9-4 9 4v4H3Z"/>')}</span><span><b>${t('Lower-cost loans')}</b><small>${t('Coming soon')}</small></span><span aria-hidden="true">&#8599;</span></button><button class="books-support-action" data-action="books-harassment"><span class="books-support-icon">${icon('<path d="m12 3 8 4v5c0 5-8 9-8 9s-8-4-8-9V7Z"/><path d="m8 12 3 3 5-5"/>')}</span><span><b>${t('Lender harassing you?')}</b><small>${t('Help through FREED')}</small></span><span aria-hidden="true">&#8599;</span></button></div>`;
}
export function healthSupportDialog(kind,t){
  if(kind==='loans')return `<div class="stack"><span class="badge">${t('Partner connection pending')}</span><p>${t('The goal: use your NiaBooks record to help you explore lower-cost borrowing with a lending partner.')}</p><p>${t('You will choose whether to share your verified income and expense records. The lender will assess eligibility and show the interest, fees, EMI and total repayment before you decide.')}</p><p>${t('Nia health does not currently unlock a loan or set its price. Loan applications are not open yet.')}</p><button data-action="close">${t('Back to NiaBooks')}</button></div>`;
  return `<div class="stack"><p>${t('FREED Shield helps people report and escalate recovery-agent harassment.')}</p><p>${t('Our referral connection is being set up. You can visit FREED directly now. NiaSave will not send your statement, score or contact details when you open this link.')}</p><p>${t('Keep the lender name, incident dates and any messages or call records ready. Share them directly with FREED only if you choose.')}</p><a class="books-partner-link" href="https://freed.care/freed-shield" target="_blank" rel="noopener noreferrer">${t('Visit FREED Shield')} ↗</a><small>${t('Opens FREED’s website. No complaint has been submitted by Nia.')}</small><button data-action="help">${t('Ask your Nia team')}</button></div>`;
}

export function booksMarkup(data,month,account,{t,esc,money}){
  const rupees=n=>money(n/100),monthLabel=m=>new Date(m+'-01T12:00:00Z').toLocaleDateString(document.documentElement.lang+'-IN',{month:'long',year:'numeric'});
  const intro=`<div class="service-intro"><div class="eyebrow">SEND · NIABOOKS</div><h1>${t('Your work. Your money. Your story.','आपका काम। आपका पैसा। आपकी कहानी।')}</h1><p>${t('See what you earn, what you spend and what reaches home.','देखें कितना कमाया, कितना खर्च हुआ और कितना घर पहुँचा।')}</p></div>`;
  if(!account)return intro+`<section class="panel stack"><h2>NiaBooks</h2><p>${t('Sign in to see your personal money statement.','अपना पैसे का विवरण देखने के लिए साइन इन करें।')}</p><button class="primary" data-action="login">${t('Sign in','साइन इन')}</button></section>`+healthSupportMarkup(t);
  if(!data?.months?.length)return intro+`<section class="panel stack"><h2>${t('Your money story starts here.','आपके पैसे की कहानी यहाँ शुरू होती है।')}</h2><p>${esc(data?.error||t('Your statement will appear when your Nia team connects verified financial records.','निया टीम से पुष्टि किए गए वित्तीय रिकॉर्ड जुड़ने पर आपका विवरण यहाँ दिखेगा।'))}</p><p class="muted">${t('No score yet. Missing information is not a low score.','अभी स्कोर नहीं है। जानकारी की कमी का मतलब कम स्कोर नहीं है।')}</p><button data-action="books-refresh">${t('Refresh statement','विवरण ताज़ा करें')}</button></section>`+healthSupportMarkup(t);
  const m=data.months.find(m=>m.month===month)||data.months.at(-1),tot=m.totals,score=data.score;
  const labels={earning:t('Earnings','कमाई'),expense:t('Expenses','खर्च'),home:t('Sent home','घर भेजा'),refund:t('Refund','वापसी')};
  const scoreReason=score.reason==='consent_required'?t('Choose whether to calculate your Nia health score.','चुनें कि आप अपना निया हेल्थ स्कोर निकालना चाहते हैं या नहीं।'):score.reason==='source_stale'?t('Refresh your records before calculating a score.','स्कोर निकालने से पहले रिकॉर्ड ताज़ा करें।'):t('We need three complete months of verified records. Missing information is not a low score.','हमें तीन पूरे महीनों के पुष्टि किए गए रिकॉर्ड चाहिए। जानकारी की कमी का मतलब कम स्कोर नहीं है।');
  return intro+`<div class="books-toolbar"><label>${t('Your monthly statement','आपका मासिक विवरण')}<select data-books-month>${[...data.months].reverse().map(x=>`<option value="${esc(x.month)}" ${x.month===m.month?'selected':''}>${esc(monthLabel(x.month))}</option>`).join('')}</select></label><button data-action="books-refresh">${t('Refresh statement','विवरण ताज़ा करें')}</button><button data-action="books-download">${t('Download statement','विवरण डाउनलोड करें')}</button></div>

  ${data.liveAvailable===false?`<p class="info">${t('Live payments could not refresh. This statement may be incomplete.')}</p>`:''}
  <p class="muted">${data.preview&&data.months.some(x=>x.entries.some(e=>e.reference.startsWith('DEMO-BOOKS-')))?t('Example statement · Fictional amounts for this demo.','उदाहरण विवरण · इस डेमो के लिए काल्पनिक राशियाँ।'):''} ${data.status==='stale'?t('Records need refreshing.','रिकॉर्ड ताज़ा करने की ज़रूरत है।'):''}</p>
  <div class="books-quick-actions"><button data-action="books-add" data-id="earning">+ ${t('Money received')}</button><button data-action="books-add" data-id="expense">+ ${t('An expense')}</button><button data-action="books-harassment">${t('Lender harassing you?')}</button></div><div class="books-dashboard"><div class="books-main"><div class="books-summary">${[['earned',t('You earned','आपने कमाया')],['spent',t('You spent','आपने खर्च किया')],['home',t('You sent home','आपने घर भेजा')],['left',t('Left after outgoings','खर्च के बाद बाकी')]].map(([key,label])=>`<section class="panel"><span>${label}</span><strong>${key==='earned'&&!m.entries.some(e=>e.kind==='earning')?t('Not recorded'):key==='left'&&!m.complete?t('Incomplete'):rupees(tot[key])}</strong></section>`).join('')}</div>
  <p class="books-note books-summary-note">${!m.complete?t('Some records are missing. Add income and outside spending to complete your picture.')+' ':''}${t('Recorded earnings − expenses − money sent home + refunds. This is a cash-flow summary, not your bank balance.','दर्ज कमाई − खर्च − घर भेजा पैसा + वापसी। यह पैसे के आने-जाने का सार है, बैंक बैलेंस नहीं।')} ${tot.refunds?t('Refunds','वापसी')+': '+rupees(tot.refunds):''}</p>
  ${planCard(t)}<section class="panel stack books-entry-tools"><h2>${t('Add income or expense')}</h2><p>${t('Live and Save payments appear automatically. Add your earnings and spending outside Nia, by date.')}</p><div class="books-add-buttons"><button data-action="books-add" data-id="earning">+ ${t('Money received')}</button><button data-action="books-add" data-id="expense">+ ${t('An expense')}</button><button data-action="books-add" data-id="home">+ ${t('Sent home')}</button></div><small>${t('Your entries are editable. Source payments are corrected by your Nia team.')}</small></section>
  <section class="panel books-statement"><h2>${t('Money in. Money out.','पैसा आया। पैसा गया।')}</h2><p class="muted">${esc(monthLabel(m.month))} · ${m.complete?t('Complete example history','पूरा उदाहरण विवरण'):t('Partial records','अधूरे रिकॉर्ड')}</p><div class="books-lines">${[...m.entries].sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<details class="books-entry"><summary><span><b>${esc(t(e.label))}</b><small>${esc(e.date)} · ${e.origin==='personal'?t('Added by you'):e.origin==='save'?t('From Save'):e.origin==='live'?t('From Live'):labels[e.kind]}${e.status!=='settled'?' · '+esc(e.status):''}</small></span><strong>${['earning','refund'].includes(e.kind)?'+':'−'}${rupees(e.amountPaise)}</strong></summary><p>${t('Source','स्रोत')}: ${esc(e.source)}<br>${t('Reference','संदर्भ')}: ${esc(e.reference)}<br>${e.origin==='personal'?t('Added by you; not independently verified'):data.preview?t('Illustrative source record','स्रोत रिकॉर्ड का उदाहरण'):esc(e.status)}</p>${e.editable?`<button data-action="books-edit" data-id="${esc(e.reference)}">${t('Edit entry')}</button>`:''}</details>`).join('')}</div>${m.pending?`<p>${t('Pending entries are excluded from totals.','लंबित प्रविष्टियाँ कुल में शामिल नहीं हैं।')}</p>`:''}<button data-action="help">${t('Something looks wrong? Ask your Nia team','कुछ गलत लग रहा है? निया टीम से पूछें')}</button></section>
  </div><aside class="books-side"><section class="panel stack books-health"><div class="row"><h2>${t('Nia health','निया हेल्थ')}</h2><span class="badge">${t('Experimental','प्रायोगिक')}</span></div>${score.status==='ready'?`<div class="books-score"><strong>${score.value}</strong><span>/ 100</span></div><p>${t('Based on your last three complete months.','आपके पिछले तीन पूरे महीनों के आधार पर।')} ${score.months?.length?esc(monthLabel(score.months[0]))+' – '+esc(monthLabel(score.months.at(-1))):''}</p><label>${t('Money retained','बचाया गया पैसा')} <b>${score.retainedPoints}/60</b><meter min="0" max="60" value="${score.retainedPoints}">${score.retainedPoints}</meter></label><label>${t('Income consistency','कमाई की नियमितता')} <b>${score.stabilityPoints}/40</b><meter min="0" max="40" value="${score.stabilityPoints}">${score.stabilityPoints}</meter></label>`:`<h3>${t('Build your money picture','अपने पैसे की तस्वीर बनाएँ')}</h3><p>${scoreReason}</p>${!data.consent?`<button data-action="books-consent" data-id="on">${t('Show my Nia health score')}</button>`:''}`}${healthSupportMarkup(t)}<p class="books-health-caption">${t('Cash-flow health. Not a credit score or loan approval.')}</p><details><summary>${t('How it works','यह कैसे काम करता है')}</summary><p>${t('Money retained: up to 60 points, reaching 60 when 20% of recorded income remains after expenses and transfers. Income consistency: up to 40 points, using the lowest monthly income divided by the highest across three months. These trial weights are not validated for lending.','बचाया गया पैसा: अधिकतम 60 अंक, जब खर्च और ट्रांसफ़र के बाद दर्ज आय का 20% बचता है। कमाई की नियमितता: तीन महीनों की सबसे कम आय को सबसे अधिक आय से भाग देकर अधिकतम 40 अंक। इन प्रयोगात्मक वज़नों की ऋण के लिए पुष्टि नहीं हुई है।')}</p><p>${t('Sending more home can lower the money-retained part of this trial score. It does not measure your contribution to your family.')}</p><p>${t('Optional. Used only for this statement; it does not change your access to Nia services.','वैकल्पिक। केवल इस विवरण के लिए; निया सेवाओं तक आपकी पहुँच नहीं बदलती।')}</p><button data-action="books-consent" data-id="${data.consent?'off':'on'}">${data.consent?t('Turn off my score','मेरा स्कोर बंद करें'):t('Show my Nia health score','मेरा निया हेल्थ स्कोर दिखाएँ')}</button></details></section><p class="books-note books-refresh-note">${t('Records refreshed','रिकॉर्ड ताज़ा किए गए')}: ${data.asOf?esc(new Date(data.asOf).toLocaleString()):t('External records not connected')}</p></aside></div>`;
}
export function downloadBooks(data,month){
  const m=data?.months?.find(m=>m.month===month)||data?.months?.at(-1);if(!m)return;
  const cell=v=>'"'+String(v).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';
  const rows=[['NiaBooks',data.preview?'ILLUSTRATIVE DEMO':'Recorded statement',m.month],['Not a bank balance. Pending/failed rows excluded from totals.'],['Date','Description','Type','Amount INR','Status','Source','Reference'],...m.entries.map(e=>[e.date,e.label,e.kind,(e.amountPaise/100).toFixed(2),e.origin==='personal'?'self-reported':e.status,e.source,e.reference]),[],['Earnings',m.totals.earned/100],['Expenses',m.totals.spent/100],['Sent home',m.totals.home/100],['Refunds',m.totals.refunds/100],['Left after outgoings',m.totals.left/100]];
  const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`NiaBooks-${m.month}${data.preview?'-example':''}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}

const entryPurposes={
  earning:['Salary','Overtime pay','Bonus','Daily wages','Other money received'],
  expense:['Food & groceries','Travel & transport','Rent outside Nia','Electricity & water','Mobile & internet','Medical expenses','Clothing & footwear','Personal care','Education','Loan repayment','Other expense'],
  home:['Family support','Household expenses at home','Medical support at home','Education at home','Other money sent home']
};
export function entryPurposeOptions(kind,value,{t,esc}){
  const choices=entryPurposes[kind]||entryPurposes.expense;
  // Keep earlier free-text entries intact when members edit them.
  const options=value&&!choices.includes(value)?[value,...choices]:choices;
  return `<option value="" ${value?'':'selected'} disabled>${t('Choose a purpose')}</option>`+options.map(label=>`<option value="${esc(label)}" ${label===value?'selected':''}>${esc(t(label))}</option>`).join('');
}

export function personalEntryForm(entry,kind,{t,esc}){
  const today=new Date(Date.now()+19800000).toISOString().slice(0,10);
  return `<form id="books-entry-form" class="stack"><input type="hidden" name="entryId" value="${esc(entry?.reference||'')}"><input type="hidden" name="revision" value="${entry?.revision||0}"><label>${t('Date')}<input type="date" name="date" min="2020-01-01" max="${today}" value="${esc(entry?.date||today)}" required></label><label>${t('Type')}<select name="kind">${[['earning',t('Money received')],['expense',t('An expense')],['home',t('Sent home')]].map(([id,label])=>`<option value="${id}" ${(entry?.kind||kind)===id?'selected':''}>${label}</option>`).join('')}</select></label><label>${t('Amount (INR)')}<input name="amount" type="number" inputmode="decimal" min="0.01" max="1000000" step="0.01" value="${entry?entry.amountPaise/100:''}" required></label><label>${t('What was it for?')}<select name="label" required>${entryPurposeOptions(entry?.kind||kind,entry?.label||'',{t,esc})}</select></label><p class="muted">${t('Add only what is missing. Live and Save payments already appear automatically.')}</p><div id="form-error" class="error-inline" role="alert"></div><button type="submit" class="primary">${t('Save entry')}</button>${entry?`<button type="button" data-action="books-remove" data-id="${esc(entry.reference)}">${t('Remove this entry')}</button>`:''}</form>`;
}
