import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import * as c from './core.mjs';
const time=Date.parse('2026-09-08T10:00:00Z');
const skus=[{id:'groundnut_oil',nia:185},{id:'nia_bathsoap',nia:52}];
const member={id:'stable-member',name:'Member',role:'member',locationIds:['S01']};
const staff={id:'operator-1',role:'admin',staff:true};
function state(){const s={beat:{beatDate:'2026-09-08',open:true,closed:false,opening:{groundnut_oil:3,nia_bathsoap:3}},orders:[],reservations:[],scans:[],payments:[],settlements:[],studios:[{id:'S01'}]};c.initialise(s,skus,true,time);return s;}
function request(s,actor=member,qty=1){const body={locationId:'S01',fulfillment:'pickup',lines:[{id:'groundnut_oil',qty}]};return {...body,fingerprint:c.quote(s,actor,body,skus,true,time).fingerprint};}
function reserve(s,actor=member,qty=1){return c.reserve(s,actor,request(s,actor,qty),randomUUID(),skus,true,time);}
function act(s,o,action,extra={}){return c.staffAction(s,staff,{orderId:o.id,action,...extra},time);}
function ready(s,o){for(const step of ['packed','loaded','at_stop'])act(s,o,step);}
test('server pricing ignores supplied prices; reserve persists once on retry',()=>{const s=state(),body=request(s);body.lines[0].nia=1;body.amount=1;const key=randomUUID();const a=c.reserve(s,member,body,key,skus,true,time);const b=c.reserve(s,member,body,key,skus,true,time);assert.equal(a.id,b.id);assert.equal(a.amount,185);assert.equal(s.orders.length,1);assert.equal(a.paid,0);assert.equal(a.payStatus,'unpaid');assert.throws(()=>c.reserve(s,member,{...body,amount:2},key,skus,true,time),/idempotency_conflict/);});
test('last unit cannot be reserved twice; failed reserve creates no record',()=>{const s=state();s.beat.opening.groundnut_oil=1;const body=request(s);reserve(s);assert.throws(()=>c.reserve(s,{...member,id:'second'},body,randomUUID(),skus,true,time),/stock_changed/);assert.equal(s.orders.length,1);});
test('read-only roles, missing identity and unassigned locations cannot reserve',()=>{const s=state();for(const actor of [null,{...member,role:'enterprise'},{...member,role:'investor'}])assert.throws(()=>c.quote(s,actor,{},skus,true,time),/member_access_required/);assert.throws(()=>request(s,{...member,locationIds:[]}),/location_unavailable/);});
test('bag validation: zero, negative, fraction, duplicate and unknown SKU',()=>{const s=state();for(const qty of [0,-1,1.5,11,'1'])assert.throws(()=>request(s,member,qty),/invalid_quantity/);const body=request(s);body.lines.push(body.lines[0]);assert.throws(()=>c.quote(s,member,body,skus,true,time),/invalid_quantity/);assert.throws(()=>c.quote(s,member,{...body,lines:[{id:'unknown',qty:1}]},skus,true,time),/product_unavailable/);});
test('price or collection window change requires new review',()=>{const s=state(),body=request(s);assert.throws(()=>c.reserve(s,member,body,randomUUID(),[{id:'groundnut_oil',nia:190}],true,time),/price_or_details_changed/);s.commerce.config.locations[0].windowEnd=new Date(time+10000).toISOString();assert.throws(()=>c.reserve(s,member,body,randomUUID(),skus,true,time),/price_or_details_changed/);});
test('member cancellation releases stock, is idempotent, and is owner scoped',()=>{const s=state(),o=reserve(s);assert.throws(()=>c.cancel(s,{...member,id:'stranger'},o.id,time),/order_not_found/);c.cancel(s,member,o.id,time);c.cancel(s,member,o.id,time);assert.equal(c.catalogue(s,skus,true,time).products[0].available,3);assert.equal(s.reservations.length,0);assert.deepEqual(c.listOrders(s,{...member,id:'stranger'}),[]);});
test('unpacked expiry releases stock; packed expiry waits for inspected return',()=>{const s=state(),one=reserve(s),two=reserve(s);act(s,two,'packed');c.expire(s,time+3*3600000);assert.equal(s.orders[0].status,'expired');assert.equal(s.orders[1].status,'return_pending');assert.equal(c.catalogue(s,skus,true,time+3*3600000).products[0].available,2);assert.throws(()=>act(s,two,'returned'),/stock_inspection_required/);act(s,two,'returned',{stockInspected:true});assert.equal(c.catalogue(s,skus,true,time+3*3600000).products[0].available,3);});
test('handover requires valid pickup code and independently verified UPI receipt',()=>{const s=state(),o=reserve(s);ready(s,o);assert.throws(()=>act(s,o,'collected',{pickupCode:o.pickupCode}),/verified_payment_required/);assert.throws(()=>act(s,o,'verify_payment',{reference:'123456789012',amount:185}),/verify_exact/);assert.throws(()=>act(s,o,'verify_payment',{reference:'123456789012',amount:1,receiptVerified:true}),/verify_exact/);act(s,o,'verify_payment',{reference:'123456789012',amount:185,receiptVerified:true});assert.equal(s.orders[0].status,'at_stop');assert.throws(()=>act(s,o,'collected',{pickupCode:'WRONG'}),/pickup_code/);act(s,o,'collected',{pickupCode:o.pickupCode});assert.equal(s.orders[0].due,0);assert.equal(s.settlements[0].matched,false);act(s,o,'reconcile',{note:'Bank statement row 8',statementVerified:true});assert.equal(s.settlements[0].matched,true);});
test('same receipt cannot fund two orders; payment retry creates one settlement',()=>{const s=state(),a=reserve(s),b=reserve(s);ready(s,a);ready(s,b);const receipt={reference:'123456789012',amount:185,receiptVerified:true};act(s,a,'verify_payment',receipt);act(s,a,'verify_payment',receipt);assert.equal(s.settlements.length,1);assert.throws(()=>act(s,b,'verify_payment',receipt),/reference_already_used/);});
test('invalid transitions and paid returns do not silently release stock',()=>{const s=state(),o=reserve(s);assert.throws(()=>act(s,o,'collected'),/invalid_order_transition/);ready(s,o);act(s,o,'verify_payment',{reference:'123456789012',amount:185,receiptVerified:true});act(s,o,'return_pending');assert.throws(()=>act(s,o,'returned',{stockInspected:true}),/refund_resolution/);act(s,o,'record_refund',{reference:'999999999001',amount:185,receiptVerified:true});assert.equal(s.orders[0].refund.reconciled,false);act(s,o,'reconcile',{note:'Refund statement row 9',statementVerified:true});act(s,o,'returned',{stockInspected:true});assert.equal(s.orders[0].status,'returned');assert.equal(s.orders[0].paid,0);});
test('live catalogue never publishes an unverified configuration',()=>{const s=state();assert.equal(c.catalogue(s,skus,false,time).ready,false);assert.equal(c.catalogue(s,skus,false,time).products.length,0);assert.throws(()=>c.configure(s,skus,{...s.commerce.config,verified:true},member,time),/admin_access/);c.configure(s,skus,{...s.commerce.config,verified:true},staff,time);assert.equal(c.catalogue(s,skus,false,time).ready,true);s.beat.closed=true;assert.equal(c.catalogue(s,skus,false,time).ready,false);});
test('expired location and disabled fulfilment are rejected',()=>{const s=state();s.commerce.config.locations[0].modes=['pickup'];assert.throws(()=>c.quote(s,member,{...request(s),fulfillment:'delivery'},skus,true,time),/location_unavailable/);s.commerce.config.locations[0].windowEnd=new Date(time-1).toISOString();assert.throws(()=>request(s),/location_unavailable/);});
test('durable snapshot retry retains member identity, order and idempotency key',()=>{const s=state(),body=request(s),key=randomUUID(),o=c.reserve(s,member,body,key,skus,true,time);const restored=JSON.parse(JSON.stringify(s));assert.equal(c.reserve(restored,member,body,key,skus,true,time).id,o.id);assert.equal(c.listOrders(restored,member)[0].id,o.id);});
test('Save categories accept new goods groups, preserve old mappings and exclude insurance checkout',()=>{
 const s=state();
 assert.equal(c.catalogue(s,skus,true,time).products.find(p=>p.id==='groundnut_oil').category,'ration');
 for(const category of ['food','ration','cleaning','personal-care','clothing','footwear','Cooking','Home care','Personal care']){
  const config=structuredClone(s.commerce.config);config.verified=true;config.products[0].category=category;
  c.configure(s,skus,config,staff,time);
  assert.equal(c.catalogue(s,skus,false,time).products.length,2);
 }
 for(const category of ['insurance','all','unknown','constructor','__proto__']){
  const config=structuredClone(s.commerce.config);config.verified=true;config.products[0].category=category;
  assert.throws(()=>c.configure(s,skus,config,staff,time),/verified_product_details_required/);
 }
});
