import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import * as core from './core.mjs';import * as books from './books.mjs';import {ownNests} from './nests.mjs';
const time=Date.parse('2026-09-09T10:00:00Z'),skus=[{id:'groundnut_oil',nia:185}];
const old={id:'old-owner',role:'member',name:'Member',locationIds:['S01']};
const current={...old,id:'new-owner',identitySource:'central-passkey',historyIds:['old-owner'],locationModes:{S01:['pickup']}};
function state(){const s={beat:{beatDate:'2026-09-09',open:true,closed:false,opening:{groundnut_oil:10}},orders:[],reservations:[],scans:[],payments:[],settlements:[]};core.initialise(s,skus,true,time);return s;}
function reserve(s,actor=old,key=randomUUID()){const b={locationId:'S01',fulfillment:'pickup',lines:[{id:'groundnut_oil',qty:1}]};const body={...b,fingerprint:core.quote(s,actor,b,skus,true,time).fingerprint};return {order:core.reserve(s,actor,body,key,skus,true,time),body,key};}
test('verified historical owners expose the exact same order, preserve retry and allow owner cancellation without reassignment',()=>{const s=state(),r=reserve(s);assert.equal(core.listOrders(s,current)[0].id,r.order.id);assert.equal(core.reserve(s,current,r.body,r.key,skus,true,time).id,r.order.id);assert.equal(s.orders.length,1);assert.equal(s.orders[0].memberId,'old-owner');assert.deepEqual(core.listOrders(s,{...current,identitySource:'legacy'}),[]);assert.deepEqual(core.listOrders(s,{...current,historyIds:[]}),[]);assert.throws(()=>core.cancel(s,{...current,historyIds:[]},r.order.id,time),/order_not_found/);core.cancel(s,current,r.order.id,time);assert.equal(s.orders[0].status,'cancelled');});
test('delivery cannot bypass the Central mode/PIN grant even when legacy location lacks a PIN list',()=>{const s=state();const body={locationId:'S01',fulfillment:'delivery',lines:[{id:'groundnut_oil',qty:1}]};assert.throws(()=>core.quote(s,current,body,skus,true,time),/location_unavailable/);const allowed={...current,locationModes:{S01:['pickup','delivery']},locationPinCodes:{S01:'560001'}};s.commerce.config.locations[0].deliveryPinCodes=['560001'];assert.equal(core.quote(s,allowed,body,skus,true,time).amount,185);assert.throws(()=>core.quote(s,{...allowed,locationPinCodes:{}},{...body,pin:'560001'},skus,true,time),/delivery_location_unverified/);});
test('history bridge preserves date entries, source expenses and original retry keys; other member records remain private',()=>{const s=state(),key=randomUUID(),body={date:'2026-09-08',kind:'expense',amountPaise:15000,label:'Travel'};books.writePersonalEntry(s,old,body,key,time);books.writePersonalEntry(s,{...old,id:'someone-else'},{...body,label:'Private'},randomUUID(),time);const r=reserve(s);s.orders[0].payment={verifiedAt:'2026-09-09T10:00:00Z',amount:185};let statement=books.ownBooks(s,current,true,time);let entries=statement.months.flatMap(m=>m.entries);assert.equal(entries.length,2);assert.equal(entries.filter(e=>e.reference==='save-payment-'+r.order.id).length,1);assert.ok(entries.every(e=>e.label!=='Private'));books.writePersonalEntry(s,current,body,key,time);assert.equal(s.commerce.books.personal['new-owner'].length,0);const personal=entries.find(e=>e.editable);books.writePersonalEntry(s,current,{...body,id:personal.reference,revision:1,amountPaise:20000},randomUUID(),time);assert.equal(s.commerce.books.personal['old-owner'][0].amountPaise,20000);assert.equal(s.commerce.books.personal['old-owner'][0].revision,2);assert.equal(books.ownBooks(s,{...current,historyIds:[]},true,time).months.flatMap(m=>m.entries).length,0);});
test('active reservations across old identities share the same limit; conflicting retry histories fail for review',()=>{const s=state();for(let i=0;i<3;i++)reserve(s);assert.throws(()=>reserve(s,current),/too_many_active_orders/);const ids=core.listOrders(s,current).map(o=>o.id);const key=randomUUID(),body={};s.commerce.requests[core.hash('old-owner:'+key)]={orderId:ids[0],hash:core.hash(JSON.stringify(body))};s.commerce.requests[core.hash('new-owner:'+key)]={orderId:ids[1],hash:core.hash(JSON.stringify(body))};assert.throws(()=>core.reserve(s,current,body,key,skus,true,time),/history_reconciliation_required/);});
test('Nest history and Living payments use exact reviewed owners; unrelated contracts remain private',()=>{
 const quote={name:'Test Nest',address:'Test address'},s={dummy:false,bookings:[{id:'b-old',source:'member_storefront',memberId:'old-owner',contractId:'c-old',studioId:'s1',nestId:'N1',arrive:'2026-09-01',depart:'2026-10-01',status:'in',memberReservation:{quote,expiresAt:'2026-10-01T00:00:00Z'}}],contracts:[{id:'c-old',signedStatus:'signed'}],collectionPayments:[{id:'payment-old',contractId:'c-old',receivableId:'rent-old',amount:2000,at:'2026-09-01T00:00:00Z',reference:'receipt-old'},{id:'private',contractId:'other',receivableId:'rent-other',amount:3000,at:'2026-09-01T00:00:00Z',reference:'private'}],receivables:[{id:'rent-old',kind:'rent'},{id:'rent-other',kind:'rent'}]};
 assert.equal(ownNests(s,current,time).bookings[0].id,'b-old');assert.deepEqual(ownNests(s,{...current,historyIds:[]},time).bookings,[]);assert.equal(books.livingEntries(s,current,false).length,1);assert.equal(books.livingEntries(s,current,false)[0].amountPaise,200000);assert.equal(s.bookings[0].memberId,'old-owner');
});
