import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { randomBytes } from 'node:crypto';
process.env.STAFF_AUTH_REQUIRED='1';
process.env.STAFF_TOKEN_SECRET=randomBytes(32).toString('base64url');
process.env.DUMMY_DATA='0';
delete process.env.DATABASE_URL;delete process.env.POSTGRES_URL;delete process.env.BISON_GOOGLE_SERVICE_ACCOUNT_JSON;
const {default:handler,issueStaffToken}=await import('./server.mjs');
test('reporting route keeps staff desk guards and fails closed without source credentials',async t=>{
  const server=http.createServer(handler);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>server.close());
  const url=`http://127.0.0.1:${server.address().port}/api/bison/current-position`;
  const admin=issueStaffToken({id:'stf-admin',email:'admin@nia.one'}),hub=issueStaffToken({id:'stf-ramesh',email:'ramesh@nia.one'});
  assert.equal((await fetch(url)).status,401);
  assert.equal((await fetch(url,{headers:{authorization:'Bearer '+hub}})).status,403);
  const result=await fetch(url,{headers:{authorization:'Bearer '+admin}});
  assert.equal(result.status,503);assert.equal(result.headers.get('cache-control'),'private, no-store');
  assert.deepEqual(await result.json(),{error:'occupancy_source_unavailable',source:'UI_Occupancy'});
  assert.equal((await fetch(url,{method:'POST',headers:{authorization:'Bearer '+admin}})).status,405);
});
