import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { randomBytes } from 'node:crypto';
process.env.STAFF_AUTH_REQUIRED = '1';
process.env.STAFF_PASSWORD = randomBytes(32).toString('base64url');
process.env.JAT_STAFF_PASSWORD = randomBytes(32).toString('base64url');
process.env.STAFF_TOKEN_SECRET = randomBytes(32).toString('base64url');
process.env.DUMMY_DATA = '0';
process.env.DEMO = '0';
delete process.env.DATABASE_URL;
delete process.env.POSTGRES_URL;
const { default: handler, issueStaffToken } = await import('./server.mjs');

test('M0 freezes Jat writes while named staff login and read access remain unchanged', async t => {
  const server = http.createServer(handler);
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => server.close());
  const base = `http://127.0.0.1:${server.address().port}`;
  const call = async (path, body, token) => {
    const r = await fetch(base + path, {method:body?'POST':'GET',headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});
    return {status:r.status, body:await r.json(), cookie:r.headers.get('set-cookie')};
  };
  assert.equal((await call('/api/bison/tower')).status,401);
  assert.equal((await call('/api/bison/data/import',{table:'members',commit:true,rows:[{member_name:'Not saved'}]})).status,503);
  assert.equal((await call('/v1/staff/login',{email:'ajay.mahawar@nia.one',password:'wrong'})).status,401);
  const login = await call('/v1/staff/login',{email:'ajay.mahawar@nia.one',password:process.env.JAT_STAFF_PASSWORD});
  assert.equal(login.status,200);
  assert.ok(login.cookie.startsWith('__Host-nia_staff_page='),'login must set host-only page session');
  assert.ok(/HttpOnly; Secure; SameSite=Strict; Max-Age=\d+$/.test(login.cookie),'page session attributes');
  assert.deepEqual(login.body.staff.desks,['living']);
  assert.equal((await call('/v1/staff/login',{email:'admin@nia.one',password:process.env.JAT_STAFF_PASSWORD})).status,401);
  assert.equal((await call('/v1/staff/login',{email:'ajay.mahawar@nia.one',password:process.env.STAFF_PASSWORD})).status,401);
  const token = login.body.token;
  const me = await call('/v1/staff/me',null,token);
  assert.ok(me.cookie.startsWith('__Host-nia_staff_page='),'existing signed bearer can open desk pages');
  const logout = await call('/v1/staff/logout',{},token);
  assert.equal(logout.status,200);
  assert.ok(logout.cookie.startsWith('__Host-nia_staff_page='),'logout must clear the page session cookie');
  assert.match(logout.cookie,/Max-Age=0$/);
  assert.equal((await call('/v1/staff/me',null,token)).status,401);
  assert.equal((await call('/api/bison/tower',null,token)).status,401);
  const crossOrigin = await fetch(base+'/v1/staff/login',{method:'POST',headers:{'content-type':'application/json',origin:'https://untrusted.invalid'},body:JSON.stringify({email:'ajay.mahawar@nia.one',password:process.env.JAT_STAFF_PASSWORD})});
  assert.equal(crossOrigin.status,403);
  assert.equal(crossOrigin.headers.get('set-cookie'),null);
  const relogin = await call('/v1/staff/login',{email:'ajay.mahawar@nia.one',password:process.env.JAT_STAFF_PASSWORD});
  assert.equal(relogin.status,200);
  const freshToken = relogin.body.token;
  const weak = await call('/v1/staff/set-password',{currentPassword:process.env.JAT_STAFF_PASSWORD,newPassword:'short'},freshToken);
  assert.equal(weak.status,400);
  const personal = await call('/v1/staff/set-password',{currentPassword:process.env.JAT_STAFF_PASSWORD,newPassword:'personal-jat-password'},freshToken);
  assert.equal(personal.status,200);
  assert.equal(personal.body.personalPassword,true);
  assert.equal((await call('/v1/staff/login',{email:'ajay.mahawar@nia.one',password:process.env.JAT_STAFF_PASSWORD})).status,401);
  const withPersonal = await call('/v1/staff/login',{email:'ajay.mahawar@nia.one',password:'personal-jat-password'});
  assert.equal(withPersonal.status,200);
  const testDesk = await call('/v1/staff/login',{email:'test.desk@nia.one',password:process.env.STAFF_PASSWORD});
  assert.equal(testDesk.status,401);
  const {testStaffPassword} = await import('../lib/staff-auth.mjs');
  const testOk = await call('/v1/staff/login',{email:'test.desk@nia.one',password:testStaffPassword()});
  assert.equal(testOk.status,200);
  assert.equal(testOk.body.staff.test,true);
  assert.equal(testOk.body.staff.email,'test.desk@nia.one');
  assert.equal((await call('/api/bison/data/import',{table:'members',commit:true,rows:[{member_name:'UAT · Jat entry'}]},withPersonal.body.token)).status,503);
  const result = await call('/api/bison/tower',null,freshToken);
  assert.equal(result.status,200);
  assert.equal(result.body.kpis.members,0);
  assert.equal((await call('/api/tower',null,freshToken)).status,403);
  assert.equal((await call('/api/dogra/state',null,freshToken)).status,403);
  const expired = issueStaffToken(login.body.staff,Date.now()-13*60*60*1000);
  assert.equal((await call('/api/bison/tower',null,expired)).status,401);
});

